name: Python Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
      - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7"]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup
      run: |
        python -m pip install --upgrade pip
        python -Im pip install nox
    - name: Run Nox Checks
      run: |
        python -Im nox --python ${{ matrix.python-version }} -t check
